stage: lats_node
output_format: cor
dimensions:
  - name: correctness
    file: correctness_cor.txt
    weight: 1.2
    extra_data:
      parser: numeric_cor
  - name: feasibility
    file: feasibility_cor.txt
    weight: 1.1
    extra_data:
      parser: numeric_cor
  - name: insightfulness
    file: insightfulness_cor.txt
    weight: 1.3
    extra_data:
      parser: numeric_cor