defaults:
  - _self_
  - db: postgres
  - plan_monitor: disabled
  - logging: json_logger
  - services: all
  - scorer: all  

  - agents/nexus_scorable_loader
  - agents/chat_analyze
  - agents/universal_scorer
  - agents/nexus
  - agents/gap

embeddings:
  backend: hnet


goal:
  goal_text: I want to build an AI that can teach itself to solve complex problems better over time.
  goal_type: "tactical"
  goal_category: "meta_learning"
  focus_area: "self_improvement"
  strategy: "stepwise_decomposition"
  difficulty: "medium-high"
  expected_formats:
    - "symbolic_prompt_plan"
    - "stepwise_reasoning_trace"
    - "annotated_score_vector"

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

pipeline:
  name: chat training
  tag: chat_training
  description: "Uses chat history to train models. Different dynamics than traditional training."
  stages:
     - name: nexus_scorable_loader
       description: "ðŸ”“ Loads a large amount of conversation turns for AB testing nexus"
       cls: stephanie.agents.scorable_loader.ScorableLoaderAgent
       enabled: true
       iterations: 1    

     - name: chat_analyze
       description: "Analyze chat history for relevant information"
       cls: stephanie.agents.knowledge.chat_analyze.ChatAnalyzeAgent
       enabled: false

     - name: universal_scorer
       cls: stephanie.agents.universal_scorer.UniversalScorerAgent
       enabled: false 
       iterations: 1

     - name: nexus
       description: "Generate a memory graph"
       cls: stephanie.components.nexus.agents.nexus_inline.NexusInlineAgent
       enabled: true
       iterations: 1

     - name: gap
       description: "Understanding the Gap between two models using chat conversation_turns"
       cls: stephanie.components.gap.gap.GapAgent
       enabled: true
       iterations: 1
