# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/arxiv_search
  - agents/document_loader
  - agents/document_profiler
  - agents/paper_score
  - agents/knowledge_loader
  - agents/mrq_trainer
  - agents/document_reward_scorer
  - agents/pipeline_judge
  - logging/json_logger

goal:
  goal_text: Iâ€™m building an AI that refines its approach over time, using feedback to improve its performance on complex tasks.
  goal_type: "tactical"
  goal_category: "meta_learning"
  focus_area: "self_improvement"
  strategy: "stepwise_decomposition"
  difficulty: "medium-high"
  expected_formats:
    - "symbolic_prompt_plan"
    - "stepwise_reasoning_trace"
    - "annotated_score_vector"

post_judgment:
  name: pipeline_judge
  enabled: true
  cls: stephanie.agents.pipeline_judge.PipelineJudgeAgent

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: rivals
  tag: "search_arxiv"
  description: "Search Arxiv for papers related to a goal"
  stages:
     - name: arxiv_search
       description: "Search Arxiv for papers related to the goal" 
       cls: stephanie.agents.knowledge.arxiv_search.ArxivSearchAgent
       enabled: true
       iterations: 1
     - name: document_loader
       description: "Load documents from the search results and summarize them"
       cls: stephanie.agents.knowledge.document_loader.DocumentLoaderAgent
       enabled: true
       iterations: 1
     - name: document_profiler
       description: "Profile the loaded documents to extract key sections"
       cls: stephanie.agents.knowledge.document_profiler.DocumentProfilerAgent
       enabled: true
       iterations: 1
     - name: paper_score
       description: "Score the papers based on their relevance and quality"
       cls: stephanie.agents.knowledge.paper_score.PaperScoreAgent
       enabled: true
       iterations: 1
     - name: knowledge_loader
       description: "Load knowledge from the scored papers into the system"
       cls: stephanie.agents.knowledge.knowledge_loader.KnowledgeLoaderAgent
       enabled: true
       iterations: 1
     - name: mrq_trainer
       description: "Build document pairs for training and evaluation" 
       cls: stephanie.agents.maintenance.mrq_trainer.MRQTrainerAgent 
       enabled: true
       iterations: 1
     - name: document_reward_scorer
       description: "Score the documents based on their relevance and quality"
       cls: stephanie.agents.knowledge.document_reward_scorer.DocumentRewardScorerAgent
       enabled: true
       iterations: 1