document_svm_trainer:
  name: document_svm_trainer
  model_path: "${hydra:runtime.cwd}/models"
  model_type: "svm"
  target_type: "document"
  dimensions: 
    - "alignment"
    - "clarity"
    - "implementability"
    - "novelty"
    - "relevance"
