# config/agents/reflection.yaml

reflection:
  name: reflection
  enabled: true
  source: database  # database or context
  batch_size: 10

  save_context: true
  skip_if_completed: false

  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null

  # Required keys for the agent ot effectively process the context
  required_keys: ["goal", "hypotheses"]   # add nodes
  # Key that it will iterate over ot generate reflections
  input_key: "hypotheses"
  # Key that it store the results of those reflections
  output_key: "reflection"

  save_prompt: true
  prompt_mode: strategy
  strategy: full_reflection  # Options: default, full_reflection, or custom
  prompt_file:
  # A set of keys that will tune the prompts operation
  preferences:
    - goal_consistency
    - factual
    - reliable_source
    - simplicity