score_comparison:
  name: score_comparison
  enabled: true
  save_prompt: true
  save_context: true
  skip_if_completed: false

  sources_to_compare:
    - sicql
    - mrq
    - svm
    - ebt
    - llm
  ground_truth_source: llm

  report_output_dir: "/reports/score_comparison"

  target_type: "document"
  dimensions: 
    - "alignment"
    - "clarity"
    - "implementability"
    - "novelty"
    - "relevance"

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: score_comparison
  prompt_mode: file
  prompt_file: score_comparison.txt