visual_introspection:
  name: visual_introspection
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/t1c/deepseek-math-7b-rl:latest
    # name: ollama/qwen3
    # name: ollama/qwen3:0.6b
    # name: ollama/t1c/deepseek-math-7b-rl
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: visual_introspection
  prompt_mode: file
  prompt_file: visual_introspection.txt

  strategy: "gsm8k_solve"
  num_examples: 10  
  split: "train"
  store_raw: true
  out_dir: "runs/visual_introspection"
  shuffle: true
  model_name: "deepseek-math:7b"
  params:
    temperature: 0.3
    max_tokens: 1024