visual_introspection:
  name: visual_introspection
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    # name: ollama/qwen3:0.6b
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: visual_introspection
  prompt_mode: file
  prompt_file: visual_introspection.txt